services:
  aivocate-postgres:
    container_name: aivocate-postgres
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: aivocate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - shared-network

  aivocate-node:
    container_name: aivocate-node
    image: node:23.10
    volumes:
      - ./:/usr/src/aivocate-node:cached
      - ./yarn_cache:/yarn:cached
    working_dir: /usr/src/aivocate-node
    command:
      - /bin/bash
      - -c
      - |
        echo 'startings' &&
        yarn config set cache-folder /yarn &&
        echo 'set cache' &&
        yarn &&
        echo 'yarn ran' &&
        yarn back:build &&
        echo 'after build' &&
        yarn db:migrate &&
        echo 'after migrate' &&
        yarn dev
    ports:
      - 8000:8000
      - 5173:5173
    networks:
      - shared-network
    depends_on:
      - aivocate-postgres

volumes:
  postgres_data:

networks:
  shared-network:
    name: shared-network
    driver: bridge
