x-logging: &default-logging
  driver: json-file
  options:
    max-size: "100m"
    max-file: "5"

services:
  aivocate-node:
    container_name: aivocate-node
    image: node:23.10
    volumes:
      - ./:/usr/src/aivocate-node:cached
      - ./yarn_cache:/yarn:cached
    working_dir: /usr/src/aivocate-node
    command:
      - /bin/bash
      - -c
      - |
        echo 'startings' &&
        yarn config set cache-folder /yarn &&
        echo 'set cache' &&
        yarn &&
        echo 'yarn ran' &&
        yarn back:build &&
        echo 'after build' &&
        yarn dev
    ports:
      - 8000:8000
      - 5173:5173
    networks:
      - aivocate-network

  aivocate-judge0:
    image: judge0/judge0:1.13.1
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    privileged: true
    logging: *default-logging
    restart: always
    depends_on:
      - aivocate-db
      - aivocate-redis
    environment:
      - RAILS_ENV=production
    networks:
      - aivocate-network

  aivocate-workers:
    image: judge0/judge0:1.13.1
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    logging: *default-logging
    restart: always
    depends_on:
      - aivocate-db
      - aivocate-redis
    environment:
      - RAILS_ENV=production
    networks:
      - aivocate-network

  aivocate-db:
    image: postgres:13.0
    env_file: judge0.conf
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    logging: *default-logging
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - aivocate-network

  aivocate-redis:
    image: redis:6.0
    command: >
      bash -c 'redis-server --appendonly yes --requirepass "$${REDIS_PASSWORD}"'
    env_file: judge0.conf
    volumes:
      - redis_data:/data
    logging: *default-logging
    restart: always
    ports:
      - "6379:6379"
    networks:
      - aivocate-network

volumes:
  postgres_data:
  redis_data:

networks:
  aivocate-network:
    name: aivocate-network
    driver: bridge
