version: '3.8'

services:
  vosk-stt:
    build: .
    container_name: vosk-stt
    ports:
      - "8765:8765"
    volumes:
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - shared-network
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; socket.create_connection(('localhost', 8765))"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  shared-network:
    external: true